### ISSUE TITLE
git clone failure

### ISSUE THREAD

**Issue by Uwinator** [guacsec/guac-data#4]
Hi there, 
I just tried to clone this repository, but I am getting errors .

Prerequisites:
Switched Proxy Off
No VPN enabled

```
$ git clone https://github.com/guacsec/guac-data.git
Cloning into 'guac-data'...
remote: Enumerating objects: 290, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 290 (delta 2), reused 1 (delta 1), pack-reused 287
Receiving objects: 100% (290/290), 98.45 MiB | 7.94 MiB/s, done.
Resolving deltas: 100% (234/234), done.
error: invalid path 'docs/cyclonedx/syft-cyclonedx-docker.io-library-alpine:latest.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
``` 

When I check the directory with `git status`, the whole repo seems to be deleted. This might be a result from the erroneous checkout.
The hint containing git restore does not work as well.

Could you please help me?

**Comment by lumjjb** [comment]
hmm... i am not able to reproduce this... Are you able to try this on another system to see if it's reproducible and to help figure out how we can reproduce it? May be a storage issue? I can only guess since I'm not able to test.

```
➜  new  git clone https://github.com/guacsec/guac-data.git
Cloning into 'guac-data'...
remote: Enumerating objects: 290, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 290 (delta 2), reused 1 (delta 1), pack-reused 287
Receiving objects: 100% (290/290), 98.45 MiB | 14.08 MiB/s, done.
Resolving deltas: 100% (234/234), done.
Updating files: 100% (177/177), done.
```

**Comment by Uwinator** [comment]
Hi, thanks for the quick response.

I tried it on a Mac and it works. However, on the initial system (Windows), I upgraded the git client and tried it again. Same result. Then I used the longpaths=true attribute for git, because this was a common cause for this kind of error message. No success here. 

I will close this issue, but if I am able to find the cause/solution, I will add it here.
