### ISSUE TITLE
Paths on windows machine prevents checkout, preventing cloning

### ISSUE THREAD

**Issue by zlehmann** [guacsec/guac-data#7]
Using git clone on a windows machine will throw the following error:

Cloning into 'guac-data'...
remote: Enumerating objects: 302, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (10/10), done.

Resolving deltas: 100% (238/238), done.
error: invalid path 'docs/cyclonedx/syft-cyclonedx-docker.io-library-alpine:latest.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.

**Comment by mlieberman85** [comment]
`docs/cyclonedx/syft-cyclonedx-docker.io-library-alpine:latest.json` the issue is `:`. Will fix in a little bit.

**Comment by mlieberman85** [comment]
Oh oops. I didn't realize citing the issue in a commit message automatically closes it.

**Comment by zlehmann** [comment]
That fixed it.
